### ISSUE TITLE
Event handler when new message sent ?

### ISSUE THREAD

**Issue by graysuit** [Eptagone/Telegram.BotAPI#1]
Respected developer @Eptagone 
Nice api.

Is there any event which would be raised when new message is sent in telegram group ?

Thanks.

**Comment by Eptagone** [comment]
Currently, this package does not include events that are called specifically when receiving a message in a group chat. However, it's easy to filter the messages to do what you want.
You will receive a message update when you receive a message from a private or group chat. To filter the messages that were sent in groups, just check that the chat type of the message is not private, in your OnMessage method.
```CSharp
protected void OnMessage(Message message)
{
    // ...
    if (message.Chat.Type != ChatType.Private) // True, if chat is a group.
    {
        // Actions for groups...
    }
    // ...
}
```
If you have a special function for group messages, call that function in that code block.
```CSharp
void OnMessage(Message message)
{
    // ...
    if (message.Chat.Type != ChatType.Private) // True, if chat is a group.
    {
        OnGroupMessage(message);
    }
    // ...
}
void OnGroupMessage(Message message) { /* ... */ }
```
Remember that to receive non-command messages in group chats, you must disable group privacy for your bot using BotFather.

**Comment by graysuit** [comment]
Thanks a lot sir.
It really helps.

And also is this possible to get array of messages in group
and choose message with specific index ?

**Comment by Eptagone** [comment]
Unfortunately, the latest Telegram Bot API (v5.1) does not have methods to do this yet. But you have at least three options to do that:
- Store all the messages you receive in a database to retrieve them later.
- If you have the message id, you can try forwarding or copying the messages to another chat. The forward and copy methods will return a copy of the message if it was successful.
- Use the Telegram Client API (user bots).

**Comment by graysuit** [comment]
I have done using telethon python.
