### ISSUE TITLE
Json Exception

### ISSUE THREAD

**Issue by Dwayne28** [Eptagone/Telegram.BotAPI#11]
I'm using long polling to get Updates. 

The crash appeared after creating an InvitationLink with Admin Approval to join.
ChatInviteLink link = Api.CreateChatInviteLink(_botProperties.PremiumChatId, null, null, null, true);

System.Text.Json.JsonException
var updates = await _api.GetUpdatesAsync(cancellationToken: stoppingToken).ConfigureAwait(false);

**Comment by Eptagone** [comment]
Hi Dwayne28. I can´t reproduce that error.
Could you provide more information? Are you using the latest version?
