### ISSUE TITLE
ParseMode is broken

### ISSUE THREAD

**Issue by litolax** [Eptagone/Telegram.BotAPI#12]
When I send message with any parseMode nothing change
```csharp
string message = $"**Пара: №1**";
await bot.SendMessageAsync(user.UserId, message, parseMode: ParseMode.HTML);
```

Result in chat:
![image](https://user-images.githubusercontent.com/60060712/188480055-62bd0c0c-2a5b-4b27-99cc-c93870912365.png)

**Comment by Eptagone** [comment]
That's because you specified HTML as your ParseMode.  But I see that you are trying to use Markdown.
Use ParseMode.Markdown instead.

**Comment by litolax** [comment]
When I use ParseMode.Markdown I have
Пара №1 without ** in chat but without bold too
When I use ParseMode.MarkdownV2
I have 
```markdown
Telegram.BotAPI.BotRequestException: Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
   at Telegram.BotAPI.BotClient.RPCA[T](String method, Object args, CancellationToken cancellationToken)
   at Telegram.BotAPI.AvailableMethods.AvailableMethodsExtensions.SendMessageAsync(BotClient api, Int64 chatId, String text, String parseMode, IEnumerable`1 entities, Nullable`1 disableWebPagePreview, Nullable`1 disableNotification,
 Nullable`1 protectContent, Nullable`1 replyToMessageId, Nullable`1 allowSendingWithoutReply, ReplyMarkup replyMarkup, CancellationToken cancellationToken)
   at StudentsTimetable.Services.ParserService.SendDayTimetable(User telegramUser) in D:\CSharp\StudentsTimetable\StudentsTimetable\Services\ParserService.cs:line 369
```
With code
```csharp
string message = $"**Пара: №{lesson.Number + 1}**";
await bot.SendMessageAsync(user.UserId, message, parseMode: ParseMode.MarkdownV2);
```

**Comment by Eptagone** [comment]
** is not allowed
Check the markdown syntax from [Telegram Bot API docs](https://core.telegram.org/bots/api#markdown-style)

\*bold text*
\_italic text_
\[inline URL]\(http://www.example.com/)
\[inline mention of a user]\(tg://user?id=123456789)
\`inline fixed-width code\`
\`\`\`
pre-formatted fixed-width code block
\`\`\`
\`\`\`python
pre-formatted fixed-width code block written in the Python programming language
\`\`\`

**Comment by litolax** [comment]
Brain lags, thx
