### ISSUE TITLE
SendGameAsync doesn't set Chat Id

### ISSUE THREAD

**Issue by TimurShaidulin** [Eptagone/Telegram.BotAPI#14]
Using both SendGameAsync methods doesn't set chat_id and the response from telegram api is "chat not found".
When I try to get ChatId from SendGameArgs object after its creation I get 0.

I have to use a workaround with custom args class derived from SendGameArgs

**Comment by Eptagone** [comment]
You are right, it's a bug. Thanks for reporting it.
It will be fixed soon, in the next release.
