### ISSUE TITLE
how to make inline keyboard button to call web_app type

### ISSUE THREAD

**Issue by rusdyrip** [Eptagone/Telegram.BotAPI#15]
i search but not found...

**Comment by Eptagone** [comment]
Hi rusdyrip. Did you try pass the web_app parameter in your inline button?
See [here](https://core.telegram.org/bots/api#keyboardbutton).

**Comment by rusdyrip** [comment]
i can't find where to put web_app parameter.
what i try to achieve is when bot send message with button. user click the button and open web_app
when i create the button to send callback data i use 
    InlineKeyboardButton.SetCallbackData
like the example
but i search there is no web_app on the availabletype :

        [JsonPropertyName("text")]
        [JsonPropertyName("url")]
        [JsonPropertyName("login_url")]
        [JsonPropertyName("callback_data")]
        [JsonPropertyName("switch_inline_query")]
        [JsonPropertyName("switch_inline_query_current_chat")]
        [JsonPropertyName("callback_game")]
        [JsonPropertyName("pay")]

**Comment by Eptagone** [comment]
Mmm. Are you using the latest version?
There should be a ’WebApp’ property in ’InlineKeyboardButton’ class, and also a ’InlineKeyboardButton.SetWebApp’

**Comment by rusdyrip** [comment]
> Mmm. Are you using the latest version? There should be a `WebApp` property in `InlineKeyboardButton` class, and also a `InlineKeyboardButton.SetWebApp` method

my mistakes.i still using ver 5.xx. already update and works great. thank you ....
