### ISSUE TITLE
Problems with notifying people

### ISSUE THREAD

**Issue by litolax** [Eptagone/Telegram.BotAPI#19]
I created /sayall command, that I use for notifying my users. Before this time I use it only for text messages, but now I try to rework it for photos, polls, etc...

Can you help me with photo send logic or maybe do you have solution for all this problem
```csharp
            var tasks = new List<Task>();

            foreach (var user in users)
            {
                tasks.Add(this._botService.SendMessageAsync(new SendMessageArgs(user.UserId, $"Уведомление: {message}")));

                if (msg.Photo is null) continue;
                foreach (var photo in msg.Photo)
                {
                    tasks.Add(this._botService.SendPhotoAsync(new SendPhotoArgs(user.UserId, photo.FileId)));
                }
            }

            await Task.WhenAll(tasks);
 ```
 When I try to send photo, I receive 3.
 
![image](https://user-images.githubusercontent.com/60060712/217819791-92751c0c-ef5b-4b08-a41b-ac01fa298618.png)
![image](https://user-images.githubusercontent.com/60060712/217819826-2034da2f-6a99-4773-98fc-af18ce015ae6.png)

**Comment by litolax** [comment]
Maybe smth missed about `mediaGroups`? Because I find `mediaGroupId` on message object that I receive, but I don't found any method that can help me to get medias from string id for send by
```csharp
tasks.Add(this._botService.BotClient.SendMediaGroupAsync(new SendMediaGroupArgs(user.Id, ???)));
```

**Comment by Eptagone** [comment]
Hi litolax.
Are you getting your msg.Photo from another message?
The Photo property contains a list of the same photo in different sizes and I see that you are sending all the photos of that property.

Are you trying to send photos from a media group?
Items in media groups are received by the bot as different messages.  Use the MediaGroupId property to see if the received message belongs to a media group and save the photos to be send.

**Comment by litolax** [comment]
You mean that I will receive a lot of updates with the same mediaGroupId and I need to somehow handle them on my own?

**Comment by Eptagone** [comment]
Exactly

**Comment by litolax** [comment]
😭

**Comment by litolax** [comment]
Thanks for the answer
