### ISSUE TITLE
sendPhoto

### ISSUE THREAD

**Issue by servim** [Eptagone/Telegram.BotAPI#2]
Hi!
How do I send a photo that has a file on my local drive?
Thank you!

**Comment by Eptagone** [comment]
Hi.
To send local files like photos or videos, you must use the **InputFile** object.

- First, read all bytes of your local file. You can use `System.IO.File.ReadAllBytes("YourFilePath");`
- Then, create an InputFile object.
- Finally, submit your photo by passing your created inputFile object.

```CSharp
using Telegram.BotAPI;
using Telegram.BotAPI.AvailableMethods;
using Telegram.BotAPI.AvailableTypes;
```

```CSharp
var myPhotoBytes = System.IO.File.ReadAllBytes("myphoto.png");
var myInputFile = new InputFile(myPhotoBytes, "myphoto.png");

myBot.SendPhoto(chatId, photo: myInputFile);
// or
myBot.SendPhoto(new SendPhotoArgs
{
  ChatId = chatId,
  Photo = myInputFile
});
```

**Comment by servim** [comment]
Thank you! It works!
