### ISSUE TITLE
I get errors when sending commands from under Webhooks

### ISSUE THREAD

**Issue by andrew-maksimov** [Eptagone/Telegram.BotAPI#22]
This error occurs when sending commands from under Webhooks. When using Long Polling everything works without errors.
I am using the latest version of the library.

`{
    "update_id": 604342142,
    "message": {
        "message_id": 1179,
        "from": {
            "id": 1750657440,
            "is_bot": false,
            "first_name": "First",
            "last_name": "Last",
            "username": "my_username",
            "language_code": "ru"
        },
        "chat": {
            "id": 1750487440,
            "first_name": "First",
            "last_name": "Last",
            "username": "my_username",
            "type": "private"
        },
        "date": 1680969814,
        "text": "/terms",
        "entities": [
            {
                "offset": 0,
                "length": 6,
                "type": "bot_command"
            }
        ]
    }
}`

400 Bad Request

`{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-e7b8697a655b0f3b2435e6511d481a04-0c5a12ae1c2cf70a-00",
    "errors": {
        "Message.Entities[0].Url": [
            "The Url field is required."
        ],
        "Message.Entities[0].User": [
            "The User field is required."
        ],
        "Message.Entities[0].Language": [
            "The Language field is required."
        ],
        "Message.Entities[0].CustomEmojiId": [
            "The CustomEmojiId field is required."
        ]
    }
}`

**Comment by Eptagone** [comment]
It's true. It'll be fixed soon

**Comment by Eptagone** [comment]
Done, the bug has just been fixed with the 3a0bf1f862dffd433402fac20130e7af671be802 commit. It is already being published on NuGet. Thank you very much for reporting it.
