### ISSUE TITLE
The type initializer for 'Telegram.BotAPI.BotClient' threw an exception.

### ISSUE THREAD

**Issue by acessors** [Eptagone/Telegram.BotAPI#23]
new BotClient("TOKEN")

**Comment by Eptagone** [comment]
Hi. BotClient can threw an exception if you try to pass a null token or other invalid parameter. Could you share for information about that exception?

**Comment by acessors** [comment]
> 

Actually the problem was with the dependencies, I didn't include all the required libs so if couldn't work (I use .NET framework 4.5). Now that I did it everything works fine
![image](https://user-images.githubusercontent.com/98286101/232333905-902ce9b9-8b6f-4776-8f8f-53adf4d60cec.png)
