### ISSUE TITLE
The IconCustomEmojiId field is required

### ISSUE THREAD

**Issue by a1ex2k** [Eptagone/Telegram.BotAPI#31]
My bot receive updates via webhook.
All messages from group topic contain an `Telegram.BotAPI.AvailableTypes.ForumTopicCreated` that has
```csharp
/// <summary>
/// Optional. Unique identifier of the custom emoji shown as the topic icon
/// </summary>
[JsonPropertyName("icon_custom_emoji_id")]
[JsonProperty(DefaultValueHandling = DefaultValueHandling.Ignore)]
public string IconCustomEmojiId { get; set; }
```
but my topics doesn't have any custom icon, so the application returns **400 Bad Request**.
That is the example of response:
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-26bb735c99c2b2cc614e741b5aa9cbed-5cdeff50b60143f7-00",
    "errors": {
        "Message.ReplyToMessage.ForumTopicCreated.IconCustomEmojiId": [
            "The IconCustomEmojiId field is required."
        ]
    }
}
```
By the way, there is no such problem when I get updates via longpoll.

Could you please make any changes to solve this?
P.S.: Topics are also created by the bot.

**Comment by a1ex2k** [comment]
Well, I've checked twice.
```csharp
public string IconCustomEmojiId { get; set; }
```
should be nullable. And finally no Bad Request.

Added a pull request. Would be nice, if you update the nuget package...

**Comment by Eptagone** [comment]
Hi @a1ex2k. Sorry for the delay.
The package will be updated in a few minutes. Thank you very much for the fix! :3
