### ISSUE TITLE
Does HelloBotNET.Webhook works for you? For me - don't 

### ISSUE THREAD

**Issue by Roman-Blinkov** [Eptagone/Telegram.BotAPI#33]
:wave: Hello Quetzal! :wave:
I see that we are removing webhook here
https://github.com/Eptagone/Telegram.BotAPI/blob/3a0d45cf49890632603dccb1c152d0adcfa7c619/src/Telegram.BotAPI.Examples/HelloBotNET.Webhook/HelloBotProperties.cs#L35-L36
And don't see any calls to Api.SetWebhook in the example.
+
I see that telegram server uses X-Telegram-Bot-Api-Secret-Token in POST and don't see handling.
Do I miss something :exploding_head:?
Thank you!

**Comment by Eptagone** [comment]
Hi, you're right!
 I think I forgot to update the examples :v
 I'll fix it. Thank you!

**Comment by Eptagone** [comment]
Hi, sorry for the delay.
I just released my README had the `ApplicationUrl` setting but the correct setting was `Telegram:WebhookUrl`.
Try with secrets like these:
```json
{
	"Telegram": {
		"WebhookUrl": "https://example.com",
		"WebhookToken": "MY_SECRET_TOKEN",
		"BotToken": "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
	}
}
```
I used a Cloudflare tunnel for testing.
I am closing this issue. Feel free to open a new one if you find any other details.
