### ISSUE TITLE
Auto retry (exponential backoff) for too many requests

### ISSUE THREAD

**Issue by pavel-zhur** [Eptagone/Telegram.BotAPI#35]
Hi,

Thank you for your awesome library, it is super helpful!
Just an idea you would maybe consider to include in your library: it would be helpful to have an optional parameter for each BotClient extension method that would make it automatically retry the requests in case the "Too Many Requests" response is received. It could work with the exponential backoff and it could maybe begin with parsing the suggested number of seconds returned in the response ("Too Many Requests: retry after 8").

Or it could be something configurable in the options for the entire BotClient.

Just thought it might be something you would consider.
Thank you!

**Comment by Eptagone** [comment]
Hi, I'm closing this issue because it's already added [here](https://github.com/Eptagone/Telegram.BotAPI/blob/6a88eb06746bf39cc90880235f4a79487035b253/src/library/Telegram.BotAPI/TelegramBotClient.API.cs#L28-L40).
It requires to pass the option `AutoRetryOnRateLimit` to the bot client.
