### ISSUE TITLE
How to get Message.Photo to file?

### ISSUE THREAD

**Issue by ketronix-dev** [Eptagone/Telegram.BotAPI#36]
How i can download picture from message in normal size?

I used this code from internet:
```c#
var download_url = $"https://api.telegram.org/file/bot{botToken}/" + file.FilePath;
using (WebClient client = new WebClient())
{
    client.DownloadFile(new Uri(download_url), @"Picure.png");
}
```

But I got a picture of a very small size...

**Comment by Eptagone** [comment]
Hi. Every `PhotoSize` in `message.Photo` has different sizes and file ids. If you don't want a small size, then choose the file id with a larger size.

**Comment by ketronix-dev** [comment]
> Hi. Every `PhotoSize` in `message.Photo` has different sizes and file ids. If you don't want a small size, then choose the file id with a larger size.

How i can do that?

```c#
var photo = update.Message.Photo;
var file = api.GetFile(photo.ToList()[0].FileId);
                            
var download_url = $"https://api.telegram.org/file/bot{botToken}/" + file.FilePath;
Console.WriteLine(download_url);
using (WebClient client = new WebClient())
{
    client.DownloadFile(new Uri(download_url), @"Picure.png");
}
```

**Comment by Eptagone** [comment]
Hi, the [PhotoSize](https://core.telegram.org/bots/api#photosize) have `width` and `height` properties. Use `Linq` to order them by their size and then get the first one to get the photo with higher resolution.
