### ISSUE TITLE
Uploading an image using multipart/form-data

### ISSUE THREAD

**Issue by MustacheAgent** [Eptagone/Telegram.BotAPI#37]
Bot is designed to send images on command from user. All images are stored in project. The following command supposed to edit message which contains inline keyboard, removing this keyboard, and then edit text and add an image.
```
var media = new InputMediaPhoto(attach);

await client.EditMessageMediaAsync(new EditMessageMediaArgs(media)
{
    ChatId = query.Message.Chat.Id,
    MessageId = query.Message.MessageId
});

await client.EditMessageTextAsync(new EditMessageTextArgs("Your image: \n")
 {
     ChatId = query.Message.Chat.Id,
     MessageId = query.Message.MessageId
 });
```
My question is: what should be passed as "attach" argument to InputMediaPhoto to achieve the goal? Some sort of binary representation of an image or something else?

**Comment by Eptagone** [comment]
Hi, in that case you will use a string like "attach://myFile". The file will be in the AttachedFiles collection [like this](https://github.com/Eptagone/Telegram.BotAPI#option-2). The name of the attached will be "myFile".

**Comment by Eptagone** [comment]
Hi, no. You have to read your file first to create an AttachedFile object.
The name of "attach://myFile" is not the path of your file. myFile is a named defined by you. That name will be used internally to create a new field.
For example:

```REST
POST: https://api.telegram.org/botTOKEN/sendPhoto

chat_id: 1234567
photo: "attach://myFile"
myFile: <stream content>
```

So, read your file using common way to read files from your filesystem and then use the bytes or stream to create an AttachedFile object and pass it into AttachedFiles parameter.

**Comment by MustacheAgent** [comment]
Thank you @Eptagone, I finally figured it out. 
So you can't just add photos by editing a message without them, so you have to send new message. Pasting the code for future generations:
```
// load file into MemoryStream in byte form
var fileStream = new MemoryStream(await File.ReadAllBytesAsync(%PATH_TO_IMAGE%);

// send photo by creating InputFile instance with image bytes provided
await client.SendPhotoAsync(new SendPhotoArgs(query.Message.Chat.Id, new InputFile(fileStream,%IMAGE_NAME%))
{
    Caption = "Your image"
});
```
%PATH_TO_IMAGE% is a string containing path to required image. If it is stored within project, make sure to set these properties: 
Build Action - Content
Copy to output directory - Copy if newer
%IMAGE_NAME% is basically any string.
