### ISSUE TITLE
Making custom requests in version 6.9.2

### ISSUE THREAD

**Issue by andrew-maksimov** [Eptagone/Telegram.BotAPI#38]
How can I making a custom request in version 6.9.2?

**Comment by Eptagone** [comment]
Hi, the custom requests feature was added in version 7 of the library.
However, the old bot client contains the following public methods.

```CSharp
GetRequestAsync
PostRequestAsync
PostRequestAsyncMultipartFormData
```

They are a little similar. You could try to use them while the final version 7 is released.

**Comment by andrew-maksimov** [comment]
Yes, this is what me need!
Thank you very much!
