### ISSUE TITLE
Can't find DeleteMessageArgs class and struggling to use DeleteMessageAsync Method

### ISSUE THREAD

**Issue by joeblack3108** [Eptagone/Telegram.BotAPI#39]
Hey there,

I've hit a bit of a snag while trying to use the deleteMessage method. It looks like the DeleteMessageArgs class has gone, which is stopping me from passing parameters to the deleteMessage method (nuget version=7.1.0.0)

docs: https://core.telegram.org/bots/api#deletemessage
path: [src/library/Telegram.BotAPI/UpdatingMessages/deleteMessage.cs](https://github.com/Eptagone/Telegram.BotAPI/blob/6a88eb06746bf39cc90880235f4a79487035b253/src/library/Telegram.BotAPI/UpdatingMessages/deleteMessage.cs#L30)

### DeleteMessageAsync
``` csharp
public static Task<bool> DeleteMessageAsync(this ITelegramBotClient client, /* args ?*/ CancellationToken cancellationToken = default)
    {
        if (client is null)
        {
            throw new ArgumentNullException(nameof(client));
        }

        return client.CallMethodAsync<bool>(MethodNames.DeleteMessage, cancellationToken: cancellationToken);
    }
```

The files are being created through auto-generation. I'm more than happy to fix this myself if you could point me in the right direction.
I'd really appreciate it if you could take a look at this. Let me know if you need any more info.

---

UPD: and few more

### GetChatMemberAsync
``` csharp
public static Task<ChatMember> GetChatMemberAsync(this ITelegramBotClient client, CancellationToken cancellationToken = default(CancellationToken))
{
    if (client == null)
    {
        throw new ArgumentNullException("client");
    }

    return client.CallMethodAsync<ChatMember>("getChatMember", null  /* args ?*/ , cancellationToken);
}
```

### SetChatAdministratorCustomTitleAsync
``` csharp
    public static Task<bool> SetChatAdministratorCustomTitleAsync(this ITelegramBotClient client, /* args ?*/ CancellationToken cancellationToken = default(CancellationToken))
    {
        if (client == null)
        {
            throw new ArgumentNullException("client");
        }

        return client.CallMethodAsync<bool>("setChatAdministratorCustomTitle", null, cancellationToken);
    }
```

And GetFileAsync too

**Comment by Eptagone** [comment]
Fixed with e5257f8! Thanks
