### ISSUE TITLE
I Want to test .net core web api, 127.0.0.1 is reserved!

### ISSUE THREAD

**Issue by poormonfared** [Eptagone/Telegram.BotAPI#4]
I want to test my application, but it has 127.0.0.1 reservations. What is your suggestion?

**Comment by Eptagone** [comment]
What do you mean by "reservations"? What message does the exception throw you?

If the port you want to use is busy, use another one.

### For testing
If you want to open a port to the internet to test your webhook, you better should try `ngrok` instead. `ngrok` is great for testing your webhook without a lot of configuration.
### For production
You have to use the ports [`443`, `80`, `88`, `8443`] to receive updates on your webhook. But that doesn't mean you should start your **ASP Net Core** on those ports. Instead, you can setup a [reverse proxy using nginx](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-6.0) or another program to forward requests to the port where the application is running. This can also help you run many webhooks on the same server.
Your server must support SSL.
