### ISSUE TITLE
FileId to InputFile

### ISSUE THREAD

**Issue by ko-vasilev** [Eptagone/Telegram.BotAPI#40]
Hi! I have a certain file already uploaded to Telegram and I have its FileId. Is there a way to initialize the `InputFile` from it, so that I don't have to download this file myself?
In the documentation (for `SendAnimation` method, for example) it says `Pass a file_id as String to send an animation that exists on the Telegram servers (recommended)`, but I don't see a way to pass the file_id

Edit: Nevermind, there is an overload that accepts a string instead of an InputFile.
But to be honest I'd expect there to be a several implementations of an InputFile one of which would accept a file id as constructor parameter

**Comment by Eptagone** [comment]
Hi. The **InputFile** class the object represents the type described in the [documentation](https://core.telegram.org/bots/api#inputfile). It says: `This object represents the contents of a file to be uploaded.`
That's why **InputFile** is only used when you want to upload new files.
