### ISSUE TITLE
Hi, can you please remove all `obsolete` files?

### ISSUE THREAD

**Issue by ohsorry** [Eptagone/Telegram.BotAPI#42]
I like your lib, can you please remove all  those `obsolete` files ( and Surgar lib? what is that?)? and make as less code files as possible? so i may contribute to this project. 🍺

**Comment by Eptagone** [comment]
Hi @ohsorry, yes.
Sugar Lib was a set of utility classes but now I'm moving all of them to the other package: **Telegram.BotAPI.Extensions**

**Comment by ohsorry** [comment]
I just finish reading the Bot API document (most of them 😅). I like the way you organize the namespaces of this lib, making source code easy to read. And you scraping the API document to generate source codes is just awesome. I decide to write my bot with this lib. 🍺

**Comment by Eptagone** [comment]
All obsolete code was removed in 94281f70e9bf3550e58604862e89a14d31fc5603. So, I'm closing this
