### ISSUE TITLE
Stopped calling OnPreCheckoutQueryAsync

### ISSUE THREAD

**Issue by andrew-maksimov** [Eptagone/Telegram.BotAPI#45]
OnPreCheckoutQueryAsync function is not called.
As a result, when you try to pay, I get "Error: PROVIDER_ACCOUNT_TIMEOUT".

Everything always worked before. Stopped working recently.
Perhaps this is due to the API update.

**Comment by Eptagone** [comment]
Hi, I tried to send a fake update in a simple test console app. The `OnPreCheckoutQueryAsync ` is called.
I also upgrade my [ShopBot](https://github.com/Eptagone/ShopBot) imitation to test with the Bot API 7.5 and it also works.
Did you try to check with Postman if Telegram is sending the update?

**Comment by andrew-maksimov** [comment]
The reason turned out to be in the payment system itself (it stopped working). I checked it on another payment system - everything still works fine.

I apologize for misunderstanding.

Thank you so much for the amazing library and its support!
