### ISSUE TITLE
How to handle the dialog with user?

### ISSUE THREAD

**Issue by litolax** [Eptagone/Telegram.BotAPI#9]
I want to send message to user with some information.
Then handle his message with needed information for me.
Like this:
```cs
await bot.SendMessageAsync(update.Message.From!.Id, "Send your group number");
//receive message from user
```
How I can handle this without `Message.ReplyToMessage`?

**Comment by Eptagone** [comment]
I think you are looking to handle user states.

Every time your bot needs to wait for a user response, you have to create a new user state and store it in a cache or a temporary database. When your bot receives a new message, it should check if the particular chat is waiting for a response and if so, handle it.

If you want to implement that feature in your bot, follow the steps below.

First, create and define two methods, one to get the last saved state and another one to handle it. See the following code:

```CSharp
//...
protected override void OnMessage(Message message)
{
    //...
    // Gets the last user state for the current chat if it exits.
    // _db.States.GetLastState is a method that you must implement using your own infrastructure.
    var state = _db.States.GetLastState(message.Chat.Id); // null if there are no pending states.
    // If there is a pending user state, handle it.
    if (state != null)
    {
        // Handle your user state.
        // OnUserState is a method for handling states that must also be defined and implemented by you.
        OnUserState(message, state);
        // If you want to skip other code after the state, then uncomment the next line.
        // return;
    }
    //...
}
```

Next, define and implement one more method that will be used to create a new state after requesting the user's response. See the following code:

```CSharp
// ...
protected override void OnCommand(Message message, string commandName, string commandParameters)
{
    switch (commandName)
    {
        // ...
        case "support":
            // Send your message to the user
            Api.SendMessage(message.Chat.Id, "Send your group number");
            // Create a new state and wait for the user response.
            _db.States.Insert(new UserState(message.Chat.Id, "support"));
            break;
        // ...
    }
}
// ...
```

With that you should be able to handle user states correctly. Once you process the state, remove it from the cache or database to avoid endless loops. Also avoid having several states at the same time. Don't create new states if one is already waiting.

You may know [@ShopBot](https://t.me/ShopBot), one of the Telegram sample bots, the */support* command starts a user state and waits for the user's response too, you can try it. From what you say, I think this is what you're looking for.

The source code of [@ShopBot](https://t.me/ShopBot) is not public but I made an imitation of that bot. You can check the source code [here](https://github.com/Eptagone/ShopBot) if you want.

**Comment by litolax** [comment]
Thanks a lot
